title: react-native-ble-manager
email: info@innove.it
description: >-
  react-native-ble-manager documentation
baseurl: "/react-native-ble-manager"
url: "https://innoveit.github.io"

theme: just-the-docs

color_scheme: dark

aux_links:
  "On GitHub":
    - https://github.com/innoveit/react-native-ble-manager

nav_external_links:
  - title: Project on GitHub
    url: https://github.com/innoveit/react-native-ble-manager
    hide_icon: false
    opens_in_new_tab: false
